import { CalendarEvent } from "@/types/calendarEventTypes";

const baseEvents: CalendarEvent[] = [
    {
        id: "1",
        title: "新2年生ガイダンス（いずれか1日）",
        start: "2026-03-25",
        end: "2026-03-28",
        allDay: true,
        backgroundColor: "var(--event-guidance)",
        textColor: "var(--event-text)",
    },
    {
        id: "2",
        title: "新2~4年生GPA成績不振者に対する事後指導期間",
        start: "2026-03-25",
        end: "2026-03-28",
        allDay: true,
        backgroundColor: "var(--event-warning)",
        textColor: "var(--event-text)",
    },
    {
        id: "4",
        title: "新入生オリエンテーション期間",
        start: "2026-04-01",
        end: "2026-04-04",
        allDay: true,
        backgroundColor: "var(--event-guidance)",
        textColor: "var(--event-text)",
    },
    {
        id: "5",
        title: "健康診断",
        start: "2026-04-01",
        end: "2026-04-04",
        allDay: true,
        backgroundColor: "var(--event-guidance)",
        textColor: "var(--event-text)",
    },
    {
        id: "6",
        title: "入学式",
        start: "2026-04-07",
        allDay: true,
        backgroundColor: "var(--event-ceremony)",
        textColor: "var(--event-text)",
    },
    {
        id: "7",
        title: "全学年:履修指導期間",
        start: "2026-04-06",
        end: "2026-04-11",
        allDay: true,
        backgroundColor: "var(--event-guidance)",
        textColor: "var(--event-text)",
    },
    {
        id: "8",
        title: "健康診断",
        start: "2026-04-06",
        end: "2026-04-11",
        allDay: true,
        backgroundColor: "var(--event-guidance)",
        textColor: "var(--event-text)",
    },
    {
        id: "9",
        title: "前期授業開始",
        start: "2026-04-13",
        allDay: true,
        backgroundColor: "var(--event-class)",
        textColor: "var(--event-text)",
    },
    {
        id: "10",
        title: "昭和の日（休日）",
        start: "2026-04-29",
        allDay: true,
        backgroundColor: "var(--event-holiday)",
        textColor: "var(--event-text)",
    },
    {
        id: "11",
        title: "憲法記念日（休日）",
        start: "2026-05-03",
        allDay: true,
        backgroundColor: "var(--event-holiday)",
        textColor: "var(--event-text)",
    },
    {
        id: "12",
        title: "みどりの日（休日）",
        start: "2026-05-04",
        allDay: true,
        backgroundColor: "var(--event-holiday)",
        textColor: "var(--event-text)",
    },
    {
        id: "13",
        title: "こどもの日（休日）",
        start: "2026-05-05",
        allDay: true,
        backgroundColor: "var(--event-holiday)",
        textColor: "var(--event-text)",
    },
    {
        id: "14",
        title: "振替休日（休日）",
        start: "2026-05-06",
        allDay: true,
        backgroundColor: "var(--event-holiday)",
        textColor: "var(--event-text)",
    },
    {
        id: "15",
        title: "創立記念式（授業なし）",
        start: "2026-05-15",
        allDay: true,
        backgroundColor: "var(--event-ceremony)",
        textColor: "var(--event-text)",
    },
    {
        id: "16",
        title: "後援会総会",
        start: "2026-06-13",
        allDay: true,
        backgroundColor: "var(--event-ceremony)",
        textColor: "var(--event-text)",
    },
    {
        id: "17",
        title: "海の日（休日）",
        start: "2026-07-20",
        allDay: true,
        backgroundColor: "var(--event-holiday)",
        textColor: "var(--event-text)",
    },
    {
        id: "18",
        title: "授業予備日(1)",
        start: "2026-07-30",
        allDay: true,
        backgroundColor: "var(--event-class)",
        textColor: "var(--event-text)",
    },
    {
        id: "19",
        title: "集中講義期間",
        start: "2026-08-04",
        allDay: true,
        backgroundColor: "var(--event-class)",
        textColor: "var(--event-text)",
    },
    {
        id: "20",
        title: "集中講義期間",
        start: "2026-08-06",
        end: "2026-08-08",
        allDay: true,
        backgroundColor: "var(--event-class)",
        textColor: "var(--event-text)",
    },
    {
        id: "21",
        title: "補講実習日",
        start: "2026-08-10",
        allDay: true,
        backgroundColor: "var(--event-class)",
        textColor: "var(--event-text)",
    },
    {
        id: "22",
        title: "山の日（休日）",
        start: "2026-08-11",
        allDay: true,
        backgroundColor: "var(--event-holiday)",
        textColor: "var(--event-text)",
    },
    {
        id: "23",
        title: "授業予備日(2)",
        start: "2026-08-12",
        allDay: true,
        backgroundColor: "var(--event-class)",
        textColor: "var(--event-text)",
    },
    {
        id: "24",
        title: "前期授業終了",
        start: "2026-08-12",
        allDay: true,
        backgroundColor: "var(--event-class)",
        textColor: "var(--event-text)",
    },
    {
        id: "25",
        title: "GPA成績不振者に対する事後指導期間",
        start: "2026-09-09",
        end: "2026-09-12",
        allDay: true,
        backgroundColor: "var(--event-warning)",
        textColor: "var(--event-text)",
    },
    {
        id: "26",
        title: "後期授業開始",
        start: "2026-09-14",
        allDay: true,
        backgroundColor: "var(--event-class)",
        textColor: "var(--event-text)",
    },
    {
        id: "27",
        title: "敬老の日（休日）",
        start: "2026-09-21",
        allDay: true,
        backgroundColor: "var(--event-holiday)",
        textColor: "var(--event-text)",
    },
    {
        id: "28",
        title: "国民の休日（休日）",
        start: "2026-09-22",
        allDay: true,
        backgroundColor: "var(--event-holiday)",
        textColor: "var(--event-text)",
    },
    {
        id: "29",
        title: "秋分の日（休日）",
        start: "2026-09-23",
        allDay: true,
        backgroundColor: "var(--event-holiday)",
        textColor: "var(--event-text)",
    },
    {
        id: "30",
        title: "9月期卒業式・学位記授与式",
        start: "2026-09-30",
        allDay: true,
        backgroundColor: "var(--event-ceremony)",
        textColor: "var(--event-text)",
    },
    {
        id: "31",
        title: "スポーツの日（休日）",
        start: "2026-10-12",
        allDay: true,
        backgroundColor: "var(--event-holiday)",
        textColor: "var(--event-text)",
    },
    {
        id: "32",
        title: "五橋祭（授業なし）",
        start: "2026-10-12",
        allDay: true,
        backgroundColor: "var(--event-ceremony)",
        textColor: "var(--event-text)",
    },
    {
        id: "33",
        title: "大学祭準備日（授業なし）",
        start: "2026-10-23",
        allDay: true,
        backgroundColor: "var(--event-ceremony)",
        textColor: "var(--event-text)",
    },
    {
        id: "34",
        title: "総合型選抜",
        start: "2026-10-23",
        allDay: true,
        backgroundColor: "var(--event-class)",
        textColor: "var(--event-text)",
    },
    {
        id: "35",
        title: "六軒丁祭",
        start: "2026-10-24",
        end: "2026-10-26",
        allDay: true,
        backgroundColor: "var(--event-ceremony)",
        textColor: "var(--event-text)",
    },
    {
        id: "36",
        title: "文化の日（休日）",
        start: "2026-11-03",
        allDay: true,
        backgroundColor: "var(--event-holiday)",
        textColor: "var(--event-text)",
    },
    {
        id: "37",
        title: "勤労感謝の日（休日）",
        start: "2026-11-23",
        allDay: true,
        backgroundColor: "var(--event-holiday)",
        textColor: "var(--event-text)",
    },
    {
        id: "38",
        title: "学校推薦型選抜（授業なし）",
        start: "2026-11-26",
        allDay: true,
        backgroundColor: "var(--event-class)",
        textColor: "var(--event-text)",
    },
    {
        id: "39",
        title: "授業予備日(1)",
        start: "2026-12-23",
        allDay: true,
        backgroundColor: "var(--event-class)",
        textColor: "var(--event-text)",
    },
    {
        id: "40",
        title: "職員クリスマス",
        start: "2026-12-24",
        allDay: true,
        backgroundColor: "var(--event-ceremony)",
        textColor: "var(--event-text)",
    },
    {
        id: "41",
        title: "集中講義期間",
        start: "2027-01-05",
        end: "2027-01-08",
        allDay: true,
        backgroundColor: "var(--event-class)",
        textColor: "var(--event-text)",
    },
    {
        id: "42",
        title: "成人の日（休日）",
        start: "2027-01-11",
        allDay: true,
        backgroundColor: "var(--event-holiday)",
        textColor: "var(--event-text)",
    },
    {
        id: "43",
        title: "大学入学共通テスト準備日（授業なし）",
        start: "2027-01-15",
        allDay: true,
        backgroundColor: "var(--event-class)",
        textColor: "var(--event-text)",
    },
    {
        id: "44",
        title: "大学入学共通テスト",
        start: "2027-01-16",
        end: "2027-01-18",
        allDay: true,
        backgroundColor: "var(--event-class)",
        textColor: "var(--event-text)",
    },
    {
        id: "45",
        title: "授業予備日(2)",
        start: "2027-01-26",
        allDay: true,
        backgroundColor: "var(--event-class)",
        textColor: "var(--event-text)",
    },
    {
        id: "46",
        title: "補講実施日(1)",
        start: "2027-01-26",
        allDay: true,
        backgroundColor: "var(--event-class)",
        textColor: "var(--event-text)",
    },
    {
        id: "47",
        title: "補講実施日(2)",
        start: "2027-01-27",
        allDay: true,
        backgroundColor: "var(--event-class)",
        textColor: "var(--event-text)",
    },
    {
        id: "48",
        title: "後期授業終了",
        start: "2027-01-27",
        allDay: true,
        backgroundColor: "var(--event-class)",
        textColor: "var(--event-text)",
    },
    {
        id: "49",
        title: "一般選抜（前期）",
        start: "2027-02-01",
        end: "2027-02-03",
        allDay: true,
        backgroundColor: "var(--event-class)",
        textColor: "var(--event-text)",
    },
    {
        id: "50",
        title: "建国記念日（休日）",
        start: "2027-02-11",
        allDay: true,
        backgroundColor: "var(--event-holiday)",
        textColor: "var(--event-text)",
    },
    {
        id: "51",
        title: "天皇誕生日（休日）",
        start: "2027-02-23",
        allDay: true,
        backgroundColor: "var(--event-holiday)",
        textColor: "var(--event-text)",
    },
    {
        id: "52",
        title: "春分の日（休日）",
        start: "2027-03-21",
        allDay: true,
        backgroundColor: "var(--event-holiday)",
        textColor: "var(--event-text)",
    },
    {
        id: "53",
        title: "振替休日（休日）",
        start: "2027-03-22",
        allDay: true,
        backgroundColor: "var(--event-holiday)",
        textColor: "var(--event-text)",
    },
    {
        id: "54",
        title: "卒業式",
        start: "2027-03-24",
        allDay: true,
        backgroundColor: "var(--event-ceremony)",
        textColor: "var(--event-text)",
    },
    {
        id: "55",
        title: "新2年生ガイダンス（いずれか1日）",
        start: "2027-03-25",
        end: "2027-03-30",
        allDay: true,
        backgroundColor: "var(--event-guidance)",
        textColor: "var(--event-text)",
    },
    {
        id: "56",
        title: "新2~4年生GPA成績不振者に対する事後指導期間",
        start: "2027-03-25",
        end: "2027-03-30",
        allDay: true,
        backgroundColor: "var(--event-warning)",
        textColor: "var(--event-text)",
    },
];

const springFirstDays = {
    月: new Date("2026-04-13"),
    火: new Date("2026-04-14"),
    水: new Date("2026-04-15"),
    木: new Date("2026-04-16"),
    金: new Date("2026-04-17"),
};

const fallFirstDays = {
    月: new Date("2026-09-14"),
    火: new Date("2026-09-15"),
    水: new Date("2026-09-16"),
    木: new Date("2026-09-17"),
    金: new Date("2026-09-18"),
};

const holidays = [
    "2026-04-29",
    "2026-05-04",
    "2026-05-05",
    "2026-05-06",
    "2026-05-15",
    "2026-07-20",
    "2026-09-21",
    "2026-09-22",
    "2026-09-23",
    "2026-10-12",
    "2026-10-23",
    "2026-11-03",
    "2026-11-23",
    "2026-11-26",
    "2026-12-23",
    "2026-12-24",
    "2026-12-25",
    "2026-12-28",
    "2026-12-29",
    "2026-12-30",
    "2026-12-31",
    "2027-01-01",
    "2027-01-05",
    "2027-01-06",
    "2027-01-07",
    "2027-01-11",
    "2027-01-15",
];

const MAX_WEEKS = 15;

const generateSemesterEvents = (
    startDays: Record<string, Date>,
    termPrefix: string,
): CalendarEvent[] => {
    let generatedEvents: CalendarEvent[] = [];

    Object.entries(startDays).forEach(([day, startDay]) => {
        let currentDate = new Date(startDay);
        let classCount = 1;

        while (classCount <= MAX_WEEKS) {
            const dateStr = currentDate.toLocaleDateString("sv-SE");

            if (!holidays.includes(dateStr)) {
                generatedEvents.push({
                    id: `class-${termPrefix}-${day}-${classCount}`,
                    title: `${day}(${classCount})`,
                    start: dateStr,
                    allDay: true,
                    backgroundColor: "var(--event-class)",
                    textColor: "var(--event-text)",
                });
                classCount++;
            }
            currentDate.setDate(currentDate.getDate() + 7);
        }
    });

    return generatedEvents;
};

const calenderEvents: CalendarEvent[] = [
    ...baseEvents,
    ...generateSemesterEvents(springFirstDays, "spring"),
    ...generateSemesterEvents(fallFirstDays, "fall"),
];
export default calenderEvents;
