export const clubs = [
    {
        name: "サークルA",
        category: "体育会系",
        status: "募集中",
        description: "サークルAの説明",
        members: 50 + "名",
        schedule: "毎週木曜日 18:00-20:00",
        location: "体育館",
        color: "bg-red-500",
        url: "/clubs/a",
    },
    {
        name: "サークルB",
        category: "文化系",
        status: "締め切り",

        description: "サークルBの説明",
        members: 30 + "名",
        schedule: "毎週金曜日 16:00-18:00",
        location: "文化館",
        color: "bg-blue-500",
        url: "/clubs/b",
    },
    {
        name: "サークルC",
        category: "ボランティア",
        status: "締め切り",
        description: "サークルCの説明",
        members: 20 + "名",
        schedule: "毎月第2水曜日 14:00-16:00",
        location: "ボランティアセンター",
        color: "bg-green-500",
        url: "/clubs/c",
    },
    {
        name: "サークルD",
        category: "その他",
        status: "募集中",
        description: "サークルDの説明",
        members: 10 + "名",
        schedule: "不定期",
        location: "その他",
        color: "bg-gray-500",
        url: "/clubs/d",
    },
];